
# DataSource : Oracle
spring.datasource.driver-class-name=ENC(k0IondzjLt6qwzgXuZObh531PQDQimtYO/hIICLj9l6jCoy09xQ90//fw9jidtXCntlv9Wwf4A4HzmYDlq8U9w==)
spring.datasource.url=ENC(RXRrW/3BxdNmzwTmPxzL0O7wQtdsHmYlHhpf8jBAiNOAupGuu64JDQzsuZ90sjqULRwgjpXlLootSxAVkEhDoUJ4MbROEE96u6KPloLMZbc=) 
spring.datasource.username=ENC(sPEOqwJc3IFb1HmZSG0GM/9ujPh3xU/MPUzPhmj9J6W/ysXJv1933bnzggBZnjRa)
spring.datasource.password=ENC(ZxcJK5Udaq05xEnhGW2KUkXOJG0CZjEiaE++0sI2r2QwNDbjKRR2PCla69d0tKz+)

#spring.autoconfigure.exclude=\
#org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration
# Mybatis : Default Setting, Override
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.type-aliases-package=com.pixcel.app
mybatis.mapper-locations=classpath:mapper/*/*.xml



# logging
#logging.level.com.pixcel.app=debug

# MultipartResolver Setting
# spring.servlet.multipart.file-size-threshold=0B
# spring.servlet.multipart.location=C:/temp
# spring.servlet.multipart.max-file-size=1MB
# spring.servlet.multipart.max-request-size=10MB

#JPA Basic Setting
#SQL, Display
spring.jpa.show-sql=true
#SQL, Easy Reading
spring.jpa.properties.hibernate.format_sql=true
#No Vender DDL
spring.jpa.generate-ddl=true
#JPA Database Setting
spring.jpa.database=oracle

#file.upload.path=D:/upload/